development:
  amazon_key: 1EYD6CA01FYNXRQ4EK82
  amazon_secret: qH4qNR1Nzty0UN1qP0LJCrKawm1hhg9B1TiMKvX6
  amazon_associate_tag: 3ds0a-20
  s3_bucket: media.3dstxt.com
  gmail_from_address_for_password_reset_and_email_alerts: 3dstxt@gmail.com
  gmail_from_address_password: SanFrancisco&m3
  secret_token: 7611a4db87ea1ed9964ad067a4a717f415e3f1ba52bcdcde2cabed0b60b0e69802ac5977977984a73b30e5cdd67e46254677bb03aea42344c1888a2f8c26566d
  
test:
  s3_bucket: media.3dstxt.com
  gmail_from_address_for_password_reset_and_email_alerts: 3dstxt@gmail.com
  gmail_from_address_password: SanFrancisco&m3
  secret_token: 7611a4db87ea1ed9964ad067a4a717f415e3f1ba52bcdcde2cabed0b60b0e69802ac5977977984a73b30e5cdd67e46254677bb03aea42344c1888a2f8c26566d
    
production:
  amazon_key: 1EYD6CA01FYNXRQ4EK82
  amazon_secret: qH4qNR1Nzty0UN1qP0LJCrKawm1hhg9B1TiMKvX6
  amazon_associate_tag: 3ds0a-20
  s3_bucket: media.3dstxt.com
  gmail_from_address_for_password_reset_and_email_alerts: 3dstxt@gmail.com
  gmail_from_address_password: SanFrancisco&m3
  secret_token: 7611a4db87ea1ed9964ad067a4a717f415e3f1ba52bcdcde2cabed0b60b0e69802ac5977977984a73b30e5cdd67e46254677bb03aea42344c1888a2f8c26566d